# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillamodel',
            name='text_form',
        ),
        migrations.AddField(
            model_name='plantillamodel',
            name='creation_date',
            field=models.CharField(default='10-07-2016', max_length=30),
        ),
        migrations.AddField(
            model_name='plantillamodel',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='751876c0-f', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='plantillamodel',
            name='public',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plantillamodel',
            name='summernote',
            field=models.TextField(blank=True, default='', max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='plantillamodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='plantillamodel',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='plantillamodel',
            name='user',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
