# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_auto_20160623_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='creation_date',
            field=models.CharField(default='26-06-2016', max_length=30),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='de8f2719-b', max_length=120, unique=True),
        ),
    ]
