# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0004_auto_20160626_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='creation_date',
            field=models.CharField(default='27-06-2016', max_length=30),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='dfc46ad6-d', max_length=120, unique=True),
        ),
    ]
