# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0006_auto_20160711_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='creation_date',
            field=models.CharField(default='13-07-2016', max_length=30),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='3ba5e22d-1', max_length=120, unique=True),
        ),
    ]
