# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0007_auto_20160713_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='073590a5-a', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='plantillas.userProfile'),
        ),
    ]
