# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0008_auto_20160713_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='44c481f2-d', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
