# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0010_auto_20160713_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='creation_date',
            field=models.CharField(default='16-02-2017', max_length=30),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='a64120bc-7', max_length=120, unique=True),
        ),
    ]
