# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0010_auto_20160627_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='creation_date',
            field=models.CharField(default='28-06-2016', max_length=30),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='e40d2831-e', max_length=120, unique=True),
        ),
    ]
