# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0012_auto_20160628_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='3971db75-d', max_length=120, unique=True),
        ),
    ]
