# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0013_auto_20170222_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(default='', upload_to='media/signatures'),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='creation_date',
            field=models.CharField(default='27-02-2017', max_length=30),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='38715167-6', max_length=120, unique=True),
        ),
    ]
