# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0014_auto_20170227_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='signature',
            new_name='firma',
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='44f6015f-6', max_length=120, unique=True),
        ),
    ]
