# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0015_auto_20170227_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='463458d7-f', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firma',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/signatures'),
        ),
    ]
