# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0017_auto_20160628_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='3a25c5f0-a', max_length=120, unique=True),
        ),
    ]
