# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0017_auto_20170227_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lugar',
        ),
        migrations.AddField(
            model_name='plantillamodel',
            name='pais',
            field=models.CharField(blank=True, choices=[('Argentina', 'Argentina'), ('Bolivia', 'Bolivia'), ('Brasil', 'Brasil'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('México', 'México'), ('Nicaragua', 'Nicaragua'), ('Panamá', 'Panamá'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('Puerto Rico', 'Puerto Rico'), ('República Dominicana', 'República Dominicana'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pais',
            field=models.CharField(blank=True, choices=[('Argentina', 'Argentina'), ('Bolivia', 'Bolivia'), ('Brasil', 'Brasil'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('México', 'México'), ('Nicaragua', 'Nicaragua'), ('Panamá', 'Panamá'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('Puerto Rico', 'Puerto Rico'), ('República Dominicana', 'República Dominicana'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='creation_date',
            field=models.CharField(default='27-03-2017', max_length=30),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='e6f13336-2', max_length=120, unique=True),
        ),
    ]
