# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0021_auto_20160628_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='creation_date',
            field=models.CharField(default='06-07-2016', max_length=30),
        ),
        migrations.AlterField(
            model_name='plantillamodel',
            name='doc_id',
            field=models.CharField(default='f858363d-9', max_length=120, unique=True),
        ),
    ]
